### PR TITLE
fix(flashblocks): handle SystemTime edge case for clock adjustments

### LINKED ISSUE #602: fix(flashblocks): Handle SystemTime edge case for clock adjustments
## Summary

Replace `SystemTime::now().duration_since(UNIX_EPOCH).unwrap()` with fallback handling to prevent panics when system clock is adjusted backward.

### Problem

Three locations call `.duration_since(UNIX_EPOCH).unwrap()` on `SystemTime::now()`. If the system clock is adjusted backward (e.g., NTP correction, VM clock sync, or leap second handling), `duration_since` returns an `Err` and the node crashes.

While rare, this is a known edge case that can occur in production environments.

### Affected Files

- `crates/builder/op-rbuilder/src/flashblocks/generator.rs` (line 473)
- `crates/builder/op-rbuilder/src/flashblocks/payload.rs` (line 656)
- `crates/client/node/src/test_utils/node.rs` (line 77)

### Current Code

```rust
let unix_now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs();
```

### Proposed Solution

Use `unwrap_or_else` with a sensible fallback. If the duration is zero, meaning the `.unwrap_or_else` is hit, log a warning.

```rust
let unix_now = SystemTime::now()
    .duration_since(UNIX_EPOCH)
    .unwrap_or_else(|e| {
        tracing::warn!(error = %e, "System clock went backward, using zero duration");
        Duration::ZERO
    })
    .as_secs();
```

### PR DESCRIPTION
**Pull request by Himess**
Closes #602

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

File: crates/client/node/src/test_utils/node.rs
Comment (refcell) [inline crates/client/node/src/test_utils/node.rs:1]: We can unwrap here since this is in a test_utils and outside the hot path

File: crates/builder/op-rbuilder/src/flashblocks/generator.rs [hunk 1]
```diff
@@ -657,7 +663,10 @@ mod tests {
     #[tokio::test]
     async fn test_job_deadline() {
         // Test future deadline
-        let now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap();
+        let now = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_else(|e| {
+            warn!(error = %e, "System clock went backward, using zero duration");
+            Duration::ZERO
+        });
```
Comment (refcell) [inline crates/builder/op-rbuilder/src/flashblocks/generator.rs]: this is fine to unwrap since we're in a test

**Comment by refcell** [comment]
Requesting @haardikk21 's review since he's more familiar with the builder code

**Comment by Himess** [comment]
Makes sense, reverted test code to use `.unwrap()`. Will change if @haardikk21 says otherwise.

File: crates/client/node/src/test_utils/node.rs
Comment (Himess) [reply crates/client/node/src/test_utils/node.rs:1]: https://github.com/base/base/pull/626/changes/035dff0eb3b3c92088806b147370c2630ff25c40

**Comment by haardikk21** [comment]
Is `Duration::ZERO` a good fallback in the case where we're expecting a unix timestamp? Wouldn't that mess things up in the flow? cc @refcell

File: crates/client/node/src/test_utils/node.rs [hunk 2]
```diff
@@ -74,7 +74,10 @@ impl LocalNode {
 
         let unique_ipc_path = format!(
             "/tmp/reth_engine_api_{}_{}_{:?}.ipc",
-            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos(),
+            std::time::SystemTime::now()
+                .duration_since(std::time::UNIX_EPOCH)
+                .unwrap()
+                .as_nanos(),
```
Comment (refcell) [inline crates/client/node/src/test_utils/node.rs]: this can still unwrap, can revert

File: crates/builder/op-rbuilder/src/flashblocks/generator.rs
Comment (refcell) [inline crates/builder/op-rbuilder/src/flashblocks/generator.rs:494]: @haardikk21 is right -- returning `Duration::ZERO` here wouldn't work. If the `unix_now` is set to zero, the returned duration will be very very large. Instead, we likely should be returning Duration::ZERO here if the system time panics (it effectively never will but just in case). This way the deadline will be `0.5s` due to the extra time allotted.

**Comment by Himess** [comment]
@refcell Done

**Comment by refcell** [comment]
Can you resolve merge conflicts @Himess ? Thanks!

**Comment by Himess** [comment]
@refcell Solved Thanks

**Review by refcell — APPROVED** [review]
This is good now, nice job
