### PR TITLE
fix: build 0 flashblocks if no time

### LINKED ISSUE #1289: fix(ci): Remove Flashblocks Test Ignore
## Summary

https://github.com/base/base/pull/1287 ignores a flakey test in ci for flashblocks.

This ticket is to implement the proper fix and remove that ignore.

### PR DESCRIPTION
**Pull request by meyer9**
When we have no time to build flashblocks, we should not build any flashblocks. Otherwise, our builder is just doing wasted work when the getPayload call will come immediately after anyway.

This fixes a test flake in CI where if the flashblock derivation started in <1 ms, the test would succeed, but >1 ms and the test would fail.

This is because (for a 1 sec block time):
- if timing is derived at 999 ms, it will give 1 ms left and build 1 tiny flashblock
- if timing is derived at 1001 ms, it will give 1s left and build the full number of flashblocks

This fixes the behavior so that 1001 ms produces 0 flashblocks.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

File: crates/builder/core/src/flashblocks/payload.rs [hunk 1]
```diff
@@ -794,14 +808,10 @@ where
         let Some(time_drift) =
             target_time.duration_since(now).ok().filter(|duration| duration.as_millis() > 0)
         else {
-            error!(
-                target: "payload_builder",
-                message = "FCU arrived too late or system clock are unsynced",
-                ?target_time,
-                ?now,
-            );
```
Comment (refcell) [inline crates/builder/core/src/flashblocks/payload.rs:802]: Should we keep this log?

Comment (meyer9) [reply crates/builder/core/src/flashblocks/payload.rs:802]: yup I just moved it so we can deduplicate the no tx pool and no flashblock code

**Comment by meyer9** [comment]
> error! log flood during chain sync (high severity)

`calculate_flashblocks` no longer has an error log.

**Review by haardikk21 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for haardikk21 @ 2026-03-17 17:29:53 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)
