### PR TITLE
fix(consensus,execution): Rename Stale Constants

### LINKED ISSUE #1600: fix(consensus,execution): Rename Stale OP_ Prefixed Constants To BASE_
## Summary

Two constants use stale `OP_`-prefixed names despite holding Base chain data: [`OP_SEPOLIA_GENESIS_HASH` and `OP_SEPOLIA_GENESIS_RPC_RESPONSE`](https://github.com/base/base/blob/main/crates/consensus/engine/src/sync/mod.rs#L130-L132) in `consensus/engine/src/sync/mod.rs` should be renamed to `BASE_SEPOLIA_GENESIS_HASH` and `BASE_SEPOLIA_GENESIS_RPC_RESPONSE`, and [`TX_SET_L1_BLOCK_OP_MAINNET_BLOCK_124665056`](https://github.com/base/base/blob/main/crates/execution/node/src/node.rs#L131) in `execution/node/src/node.rs` should be renamed to `TX_SET_L1_BLOCK_BASE_MAINNET_BLOCK_124665056`. These are test/internal constants so the rename carries no external breaking change.

### PR DESCRIPTION
**Pull request by refcell**
## Summary

Two constants held OP chain data under stale or mismatched names. This replaces the OP Sepolia genesis hash and RPC response in \`consensus/engine/src/sync/mod.rs\` with real Base Sepolia genesis data (hash \`0x0dcc9e08...\`), and replaces the OP Mainnet \`setL1Block\` transaction in \`execution/node/src/node.rs\` with the actual deposit transaction at index 0 from Base Mainnet block 1, renaming the constant to \`TX_SET_L1_BLOCK_BASE_MAINNET_BLOCK_1\`. All affected symbols are internal test or dev-mode constants with no external API surface.

Closes #1600.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

File: crates/consensus/engine/src/sync/mod.rs [hunk 1]
```diff
@@ -127,9 +127,9 @@ mod tests {
...
...0x4200000000000000000000000000000000000011\",\"stateRoot\":\"0x06787a17a3ed87c339a39dbbeeb311578a0c83ed29daa2db95da62b28efce8a9\",\"transactionsRoot\":\"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\",\"receiptsRoot\":\"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\",\"logsBloom\":\"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"difficulty\":\"0x0\",\"number\":\"0x0\",\"gasLimit\":\"0x1c9c380\",\"gasUsed\":\"0x0\",\"timestamp\":\"0x64d6dbac\",\"extraData\":\"0x424544524f434b\",\"mixHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":\"0x0000000000000000\",\"baseFeePerGas\":\"0x3b9aca00\",\"size\":\"0x209\",\"uncles\":[],\"transactions\":[]}";
```
Comment (danyalprout) [inline crates/consensus/engine/src/sync/mod.rs]: should we change the value too? I'm assuming this is still op?

Comment (refcell) [reply crates/consensus/engine/src/sync/mod.rs]: Yes, done!

**Review by danyalprout — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for danyalprout @ 2026-03-30 15:06:44 UTC
User failed mfa authentication, either user does not exist or public email is not set on your github profile. `\
        `see [go/mfa-help](http://go/mfa-help)

**Review by danyalprout — APPROVED** [review]
