### PR TITLE
fix: eth_getBlockByNumber should return Latest if Pending is None

### LINKED ISSUE #178: `eth_getBlockByNumber` should return `Latest` if `Pending` is `None`
At block boundaries, if canonical blocks catch up to the pending state, it clears the pending blocks and sets it to `None`

If a user requests `eth_getBlockByNumber` at this point with the `pending` block tag, they will receive a `null` which forces them to retry again

Geth's behaviour appears to be to just return the `latest` block when fetching `pending` - as L2s dont really have a pending block in non-flashblocks mode anyway due to not having a public mempool. We should match that behavior by falling through to fetching `Latest` when `Pending` is `None`

### PR DESCRIPTION
**Pull request by Parizval**
Closes #178 

get_block_by_number() function is updated to match the Geth's behaviour of returning Latest Block.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>1</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>2</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

File: crates/flashblocks-rpc/src/rpc.rs [hunk 1]
```diff
@@ -178,7 +178,14 @@ where
         if number.is_pending() {
             self.metrics.get_block_by_number.increment(1);
             let pending_blocks = self.flashblocks_state.get_pending_blocks();
-            Ok(pending_blocks.get_block(full))
+            if pending_blocks.as_ref().is_some() {
+                Ok(pending_blocks.get_block(full))
+            } else {
```
Comment (haardikk21) [inline crates/flashblocks-rpc/src/rpc.rs]: We dont need the else here or the explicit return statement

**Review by haardikk21 — DISMISSED** [review]
minor nit

**Review by danyalprout — APPROVED** [review]
lgtm, thank you!
