### PR TITLE
fix(client): Flashblocks WS RPC Subscriptions

### LINKED ISSUE #613: fix(flashblocks): eth_subscribe for flashblock types should closely mirror non FB variants
### New Flashblock Transactions
`{"jsonrpc":"2.0", "id": 1, "method": "eth_subscribe", "params": ["newFlashblockTransactions"]}`

* Stream of transaction data
* Can be enriched with transaction and log (lets dedup the fields here) info by passing full=true
* Should return one transaction per websocket message

### Pending Logs
`{"jsonrpc":"2.0", "id": 1, "method": "eth_subscribe", "params": ["pendingLogs", {"address": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913", "topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}]}`

* Stream of logs in Flashblocks that match the filter
* Should return one matching log per websocket message (similar to logs)

### New Flashblocks
`{"jsonrpc":"2.0", "id": 1, "method": "eth_subscribe", "params": ["newFlashblocks"]}`

* Should return the current RPC block as it's modifying on each new message ✅

### PR DESCRIPTION
**Pull request by refcell**
## Summary

Closes #613

This PR fixes the flashblocks WebSocket subscription RPCs to emit one item per message instead of arrays, aligning with how standard Ethereum subscription variants work -- `newFlashblockTransactions` (both hash-only and full) and `pendingLogs` now stream individual transactions/logs per WebSocket message by flat-mapping the internal batch streams, with corresponding test updates to validate the new per-item format.

This change also needs to be backported to `0.3.0` I believe.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by haardikk21** [comment]
Is this overlapping with the work @danyalprout was doing? 

We also need to include logs in the `newFlashblockTransactions` method if `full = true` - which should probably be in the same PR

File: crates/client/flashblocks/src/rpc/pubsub.rs [hunk 1]
```diff
@@ -91,76 +92,98 @@ impl<Eth, FB> EthPubSub<Eth, FB> {
...
+                        Ok(blocks) => blocks,
+                        Err(err) => {
+                            error!(
+                                message = "Error in flashblocks stream for pending logs",
+                                error = %err
+                            );
+                            return None;
+                        }
+                    };
+                    let logs = pending_blocks.get_pending_logs(&filter);
```
Comment (danyalprout) [inline crates/client/flashblocks/src/rpc/pubsub.rs]: I think this pending method will cause duplicates to be sent as it gets called with the full pending block on each new Flashblock. E.g.

Fb1=(a)
Fb2=(b)

I believe this will cause us to send

a, a, b

I think we need to narrow it down to just the transactions in the latest FB 

Same with the get pending transaction hashes too

**Review by danyalprout — COMMENTED** [review]
It would be great if we could also extend the full transaction data to have the log info too.

Happy to do that in a follow up

**Review by danyalprout — DISMISSED** [review]

**Review by danyalprout — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for danyalprout @ 2026-01-30 10:20:31 UTC
User cannot review their own commit

**Comment by danyalprout** [comment]
Cut a release branch for this [here](https://github.com/base/base/tree/releases/v0.3.1).

**Review by haardikk21 — APPROVED** [review]
