### PR TITLE
fix(infra): remove pub(crate) visibility in basectl and websocket-proxy

### LINKED ISSUE #2062: ktlo(infra): Remove Pub Crate In Basectl
## Summary

crates/infra/basectl uses pub(crate) throughout its app and TUI modules (over 20 files). Per CLAUDE.md all items must be pub with no pub(crate). crates/infra/websocket-proxy has the same issue in one file.

Representative files: [crates/infra/basectl/src/app/action.rs](https://github.com/base/base/blob/main/crates/infra/basectl/src/app/action.rs), [crates/infra/basectl/src/app/core.rs](https://github.com/base/base/blob/main/crates/infra/basectl/src/app/core.rs), [crates/infra/basectl/src/tui/mod.rs](https://github.com/base/base/blob/main/crates/infra/basectl/src/tui/mod.rs), [crates/infra/websocket-proxy/src/client.rs](https://github.com/base/base/blob/main/crates/infra/websocket-proxy/src/client.rs).

Change all pub(crate) items to pub and ensure proper re-exports from each crate's lib.rs.

### PR DESCRIPTION
**Pull request by crazywriter1**
Closes #2062

## Summary
- Replace all pub(crate) with pub across basectl (28 files) and websocket-proxy (1 file)
- Re-export all newly public items from lib.rs per CLAUDE.md conventions
- Fix clippy warnings (unreachable_pub, missing_docs, missing Debug/Default impls)

Previous PR #2083 was closed by the vouch bot. Rebased onto latest main and all clippy warnings resolved.

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>✅ Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
✅
<code>1/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by mw2000 — DISMISSED** [review]
Thanks for the PR! The `pub(crate)` → `pub` conversion is the right direction per our AGENTS.md conventions. However, the re-export strategy needs some changes before this can merge.

## Blockers

### 1. `lib.rs` uses glob re-exports (`pub use foo::*`)

AGENTS.md requires grouping each module declaration with its explicit re-export:

```rust
mod foo;
pub use foo::Bar;
```

The current `pub use app::*`, `pub use commands::*`, `pub use rpc::*`, etc. violate this — and worse, they silently leak any future internal type into the crate's public API. Please replace each glob with an explicit list of the types/functions being re-exported.

### 2. `pub mod common` in `commands/mod.rs`

AGENTS.md says modules must not be `pub` or `pub(crate)` unless they are test utilities. The items inside `common` should be re-exported from the parent module, but the module itself should stay private:

```rust
mod common;
pub use common::{FlashblockEntry, DaTracker, /* ... */};
```

### 3. `pub use views::*` in `app/mod.rs`

Same glob issue as #1. Please enumerate the specific view types being re-exported.

## Non-blocking

- The massive API surface expansion (~100+ newly public types) is worth a quick sanity check — are all of these intended to be stable public API, or should some remain internal? Not a blocker, just worth confirming intent.
- Bare public functions in `rpc.rs` / `l1_client.rs` are pre-existing and not introduced here, so not blocking this PR.

## What's good

- The `pub(crate)` → `pub` conversion itself is correct and consistent.
- Missing `Debug` derive on `FlashblocksView` and `Default` on `LoadTestView` — good catches.
- Manual `Debug` impl on `App` is well done.
- The websocket-proxy change is clean.

The fix should be straightforward — just swap the globs for explicit type lists. Happy to re-review once that's updated.

File: crates/infra/basectl/src/lib.rs [hunk 1]
```diff
@@ -1,12 +1,19 @@
 #![doc = include_str!("../README.md")]
 
 mod app;
-pub use app::{ViewId, run_app, run_flashblocks_json};
+pub use app::*;
```
Comment (mw2000) [inline crates/infra/basectl/src/lib.rs]: AGENTS.md requires explicit re-exports grouped with their module declarations (`mod foo; pub use foo::Bar;`), not glob re-exports. `pub use app::*` silently leaks any future internal type into the crate root. Please enumerate the specific types being re-exported.

Same applies to `pub use commands::*`, `pub use l1_client::*`, `pub use rpc::*`, and `pub use tui::*` below.

File: crates/infra/basectl/src/commands/mod.rs [hunk 2]
```diff
@@ -1,4 +1,4 @@
 //! CLI command implementations for the basectl tool.
 
 /// Shared types, formatters, and rendering utilities for CLI commands.
-pub(crate) mod common;
+pub mod common;
```
Comment (mw2000) [inline crates/infra/basectl/src/commands/mod.rs]: AGENTS.md: *"Modules must not be `pub` or `pub(crate)` unless they are test utilities."* This should stay as `mod common;` with the public items re-exported explicitly from this module:
```rust
mod common;
pub use common::{FlashblockEntry, BlockContribution, DaTracker, ...};
```

File: crates/infra/basectl/src/app/mod.rs [hunk 3]
```diff
@@ -1,23 +1,25 @@
...
-pub use runner::{run_app, run_flashblocks_json};
+pub use runner::{run_app, run_flashblocks_json, start_background_services};
 
 mod view;
-pub(crate) use view::View;
+pub use view::View;
 
 /// TUI view implementations.
 mod views;
+pub use views::*;
```
Comment (mw2000) [inline crates/infra/basectl/src/app/mod.rs]: `pub use views::*` has the same glob re-export problem. Please list the specific view types being re-exported:
```rust
pub use views::{CommandCenterView, ConductorView, ConfigView, DaMonitorView, FlashblocksView, HomeView, LoadTestView, ProofsView, TransactionPane, UpgradesView, create_view};
```

**Comment by cb-heimdall** [comment]
Review Error for mw2000 @ 2026-04-12 00:45:03 UTC
User failed mfa authentication, see [go/mfa-help](http://go/mfa-help)

**Comment by crazywriter1** [comment]
Thanks for the review sir. Addressed all review feedback:
- Replaced all glob re-exports (`pub use foo::*`) with explicit type lists in lib.rs and app/mod.rs
- Made `commands::common` module private with explicit re-exports
- Updated all internal imports from `commands::common::` to `commands::`
@mw2000

**Review by refcell — APPROVED** [review]
